version: "3.8"

services: 
  hfl_mockup:
    container_name: "test"
    build: 
      context: ../../
      dockerfile: ./baseimages/cpu_machine/Dockerfile
      args: 
        - USER=$USER
    shm_size: "8gb"
    ports:
      - "8080:8080"
    volumes:
      - ../../shell:/home/$USER/project/shell
      - ../../data:/home/$USER/project/data/
      - ../../data/CIFAR10/partitions:/home/$USER/project/data/CIFAR10/partitions:ro
      - ../../data/FashionMNIST/partitions:/home/$USER/project/data/FashionMNIST/partitions:ro
      - ../../data/MNIST/partitions:/home/$USER/project/data/MNIST/partitions:ro
      - ../../local/:/home/$USER/project/local/
      - ../../src:/home/$USER/project/src/
      - ../../.vscode:/home/$USER/project/.vscode
    secrets:
      - wandb_api_key
    environment:
      - DATA_ROOT=/home/$USER/project/data
      - WANDB_API_KEY_FILE=/run/secrets/wandb_api_key

secrets:
  wandb_api_key:
    file: ../.wandb_api_key